### ISSUE TITLE
repeats

### ISSUE THREAD

**Issue by KewTeacher** [Comp-Sci-Principles-2018-19/project-JoyWu23#2]
Expand your program as such
ask the user to input each value, then it returns the number of trees
then ask the user if they want to continue.
If yes, ask for each value again
Id no, say "goodbye" and end the program

**Comment by JoyWu23** [comment]
Done

**Comment by KewTeacher** [comment]
after the user is done, print out a list of the number of trees for each time through

**Comment by JoyWu23** [comment]
I did it

**Comment by KewTeacher** [comment]
write a new function that takes in this data:
[(7,5,10),(4,5,6),(10,4,8),(20,56,7),(45,8789,450),(0,0,0)]
and returns a list of the number of trees

**Comment by lanoflatfaceo** [comment]
I get an error when I input 150 or larger:

How many pounds of carbon dioxide are in the atmosphere?150
What is the rate at which the amount of carbon dioxide increases in the atmosphere per year?150
By how many years do you want the amound of carbon dioxide in the atmosphere to be balanced out?150
Traceback (most recent call last):
  File "C:\Users\Da-Hong Setoo\Documents\GitHub\project-JoyWu23\project.py", line 35, in <module>
    print("The amount of trees you need for there to be a safe amount of carbon dioxide in the air in", time, "years is", calc_trees(co2,rate,time))
  File "C:\Users\Da-Hong Setoo\Documents\GitHub\project-JoyWu23\project.py", line 18, in calc_trees
    return (c*(r+1)**t)/(t*20)
OverflowError: (34, 'Result too large')
>>>

**Comment by JoyWu23** [comment]
The function is designed so that the rate at which the amount of carbon dioxide increases that you input should be in decimals, not percentage. Therefore, putting 150 for the rate results in too large of a number.
